### ISSUE TITLE
Mapping pointer values

### ISSUE THREAD

**Issue by Ellencj** [samonzeweb/godb#50]
I had a problem where a column sometimes had float values and sometimes NULL values, something which should have been easily solved by using a pointer in my row struct. However for some reason this bit of code in newStructMappingDetails() in dbreflect.go prevents the use of pointers:
```
 // Only non pointers are mapped
if fieldInfo.Type.Kind() == reflect.Ptr {
	continue
}
```
Leaving this code in will return an "unknown column name" error when a row with a value shows up, and commenting it out works well for my purposes. Is there a reason pointers aren't mapped? This is so specific that I feel there must be some thought behind it. If not I would happily provide the worlds smallest pull request.

**Comment by samonzeweb** [comment]
The way to manage null value in Go, especially with SQL, is using something like sql.NullFloat64 : https://golang.org/pkg/database/sql/#NullFloat64 . More about this here : http://go-database-sql.org/nulls.html

Another reason godb does not manage pointer, because it would have to manage allocation, doing more reflection, resulting in slower execution.

**Comment by Ellencj** [comment]
Aha, that does make sense, and work! :) thanks
